<a href="https://colab.research.google.com/github/Rudransh840/ML--Lab/blob/main/ML_Lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

In [2]:
# Column names
columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

In [3]:
# Load dataset
from sklearn.datasets import load_iris

# Load the IRIS Dataset from sklearn
iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data['species'] = iris.target

# Map numerical species to their names
species_map = {i: name for i, name in enumerate(iris.target_names)}
data['species'] = data['species'].map(species_map)

In [4]:
# Remove empty rows
data = data.dropna()

In [5]:
# Features and target
X = data.iloc[:, 0:4].values
y = data.iloc[:, 4].values

In [6]:
# Encode species labels
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [7]:
# Convert to categorical (for CNN output layer)
y = to_categorical(y)

In [8]:
# Feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [9]:
# Reshape for CNN (samples, steps, channels)
X = X.reshape(X.shape[0], X.shape[1], 1)

In [10]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
# CNN Model
model = Sequential()

model.add(Conv1D(filters=32, kernel_size=2, activation='relu', input_shape=(4,1)))
model.add(MaxPooling1D(pool_size=2))

model.add(Flatten())

model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [13]:
# Train model
model.fit(X_train, y_train, epochs=50, batch_size=5, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3583 - loss: 1.1209
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4583 - loss: 1.0405 
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4833 - loss: 0.9944 
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6000 - loss: 0.9511 
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6167 - loss: 0.9194 
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6500 - loss: 0.8886 
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6250 - loss: 0.8559 
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.8315 
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6833 - loss: 0.8025 
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6833 - loss: 0.7797 
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6917 - loss: 0.7579 
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0

In [14]:
# Prediction
y_pred = model.predict(X_test)

y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step


In [15]:
# Evaluation
print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_classes, y_pred_classes))

print("\nClassification Report:")
print(classification_report(y_test_classes, y_pred_classes))

Accuracy: 0.7666666666666667

Confusion Matrix:
[[7 3 0]
 [1 8 0]
 [2 1 8]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.70      0.70        10
           1       0.67      0.89      0.76         9
           2       1.00      0.73      0.84        11

    accuracy                           0.77        30
   macro avg       0.79      0.77      0.77        30
weighted avg       0.80      0.77      0.77        30

